import 'dotenv/config';
import express from 'express';
import http from 'node:http';
import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {WebSocketServer} from 'ws';
import {ObsManagerPool} from './lib/obs-manager.js';
import {DEFAULT_MUSIC_STATE,normalizePlaylist,advanceState,startPlaylist} from './lib/music.js';
import {atomicWriteJson,readJson,ensureJson,loadOrCreateSecret,sealText,openText,safeText,clamp,audioExtension,looksLikeAudio,isRtmpUrl,timingSafeEqualText,uniqueStrings} from './lib/core.js';

const VERSION='5.0.0-rc.1';
const PORT=Number(process.env.PORT||3000);
const REMOTE_PIN=String(process.env.REMOTE_PIN||'');
const OPENAI_API_KEY=String(process.env.OPENAI_API_KEY||'');
const AI_MODEL=String(process.env.AI_MODEL||'gpt-5-mini');
const ROOT=process.cwd();
const DATA=path.join(ROOT,'data');
const MEDIA=path.join(DATA,'media');
const SOUND_DIR=path.join(MEDIA,'sounds');
const MUSIC_DIR=path.join(MEDIA,'music');
const LEGACY_SOUND=path.join(ROOT,'public','uploads','sounds');
const LEGACY_MUSIC=path.join(ROOT,'public','uploads','music');
const DB={sounds:path.join(DATA,'sounds.json'),music:path.join(DATA,'music.json'),playlists:path.join(DATA,'playlists.json'),destinations:path.join(DATA,'destinations.json'),musicState:path.join(DATA,'music-state.json'),playerSecret:path.join(DATA,'player-secret'),vaultKey:path.join(DATA,'vault-key')};
for(const d of [DATA,SOUND_DIR,MUSIC_DIR])fs.mkdirSync(d,{recursive:true});
ensureJson(DB.sounds,[]);ensureJson(DB.music,[]);ensureJson(DB.playlists,[]);ensureJson(DB.destinations,[]);ensureJson(DB.musicState,DEFAULT_MUSIC_STATE);
const PLAYER_SECRET=loadOrCreateSecret(DB.playerSecret,32).toString('base64url');
const VAULT_KEY=loadOrCreateSecret(DB.vaultKey,32);

function migrateLegacyDir(from,to){if(!fs.existsSync(from))return;for(const name of fs.readdirSync(from)){const src=path.join(from,name),dst=path.join(to,path.basename(name));try{if(fs.statSync(src).isFile()&&!fs.existsSync(dst))fs.renameSync(src,dst)}catch{}}}
migrateLegacyDir(LEGACY_SOUND,SOUND_DIR);migrateLegacyDir(LEGACY_MUSIC,MUSIC_DIR);

function parseTargets(){if(process.env.OBS_TARGETS_JSON){try{const p=JSON.parse(process.env.OBS_TARGETS_JSON);if(Array.isArray(p)&&p.length)return p.map((t,i)=>({id:String(t.id||`obs-${i+1}`),name:String(t.name||`OBS ${i+1}`),url:String(t.url||'ws://127.0.0.1:4455'),password:String(t.password||'')}))}catch(error){console.error('Invalid OBS_TARGETS_JSON:',error.message)}}return[{id:'main',name:process.env.OBS_NAME||'Mac mini OBS',url:process.env.OBS_WS_URL||'ws://127.0.0.1:4455',password:process.env.OBS_WS_PASSWORD||''}]}
const TARGETS=parseTargets();
const pool=new ObsManagerPool(TARGETS);

const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'48mb',strict:true}));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(self), microphone=(self)');res.setHeader('Cross-Origin-Resource-Policy','same-origin');next()});app.use(express.static('public',{extensions:['html'],etag:true,maxAge:process.env.NODE_ENV==='production'?'5m':0}));

const authFailures=new Map();function authBucket(ip){const now=Date.now(),old=authFailures.get(ip)||{count:0,at:now};if(now-old.at>60_000)return{count:0,at:now};return old}function noteAuthFailure(ip){const b=authBucket(ip);b.count++;b.at=Date.now();authFailures.set(ip,b);return b.count}function requirePin(req,res,next){if(!REMOTE_PIN)return next();const ip=req.ip||req.socket.remoteAddress||'unknown',b=authBucket(ip);if(b.count>=12)return res.status(429).json({error:'Too many authentication attempts. Wait a minute and try again.'});const pin=String(req.headers['x-remote-pin']||'');if(!timingSafeEqualText(pin,REMOTE_PIN)){noteAuthFailure(ip);return res.status(401).json({error:'Unauthorized'})}authFailures.delete(ip);next()}

const server=http.createServer(app);const wss=new WebSocketServer({server,path:'/ws'}),soundWss=new WebSocketServer({server,path:'/sound-player'}),musicWss=new WebSocketServer({server,path:'/music-player'});const clients=new Set(),soundPlayers=new Set(),musicPlayers=new Set();
const send=(ws,p)=>{if(ws?.readyState===1)ws.send(JSON.stringify(p))};const broadcast=(set,p)=>{for(const ws of set)send(ws,p)};function broadcastClients(payload,targetId=null){for(const ws of clients)if(!targetId||String(ws.targetId)===String(targetId))send(ws,payload)}
function playerAuthorized(req){try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);return timingSafeEqualText(u.searchParams.get('token')||'',PLAYER_SECRET)}catch{return false}}
soundWss.on('connection',(ws,req)=>{if(!playerAuthorized(req)){ws.close(1008,'Unauthorized');return}soundPlayers.add(ws);ws.on('close',()=>soundPlayers.delete(ws))});
musicWss.on('connection',(ws,req)=>{if(!playerAuthorized(req)){ws.close(1008,'Unauthorized');return}musicPlayers.add(ws);sendMusicState(ws);ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='progress')updateMusicProgress(m);if(m.type==='ended')advanceMusic(1)}catch{}});ws.on('close',()=>musicPlayers.delete(ws))});

function list(db,fallback=[]){return readJson(db,fallback)}function save(db,value){atomicWriteJson(db,value)}
function musicPayload(){const state={...DEFAULT_MUSIC_STATE,...readJson(DB.musicState,DEFAULT_MUSIC_STATE)},tracks=list(DB.music),playlists=list(DB.playlists),track=tracks.find(x=>x.id===state.trackId)||null,playlist=playlists.find(x=>x.id===state.playlistId)||null;return{state,track,playlist,tracks,playlists}}
function playerMusicPayload(){const p=musicPayload();return{state:p.state,track:p.track?{...p.track,url:`/internal/media/music/${encodeURIComponent(p.track.filename)}?token=${encodeURIComponent(PLAYER_SECRET)}`}:null,playlist:p.playlist}}
function sendMusicState(ws){send(ws,{type:'state',...playerMusicPayload()})}function broadcastMusic(){broadcast(musicPlayers,{type:'state',...playerMusicPayload()});const p=musicPayload();broadcastClients({type:'music-state',state:p.state,track:p.track,playlist:p.playlist})}
function setMusicState(patch){const state={...DEFAULT_MUSIC_STATE,...readJson(DB.musicState,DEFAULT_MUSIC_STATE),...patch};state.volume=clamp(state.volume,0,100,25);state.position=Math.max(0,Number(state.position)||0);state.duration=Math.max(0,Number(state.duration)||0);save(DB.musicState,state);broadcastMusic();return state}
function updateMusicProgress(m){const current=readJson(DB.musicState,DEFAULT_MUSIC_STATE);const pos=Math.max(0,Number(m.position)||0),dur=Math.max(0,Number(m.duration)||0);if(Math.abs(pos-(current.position||0))<.35&&Math.abs(dur-(current.duration||0))<.35&&Boolean(m.playing)===Boolean(current.playing))return;save(DB.musicState,{...current,position:pos,duration:dur,playing:Boolean(m.playing)});const p=musicPayload();broadcastClients({type:'music-state',state:p.state,track:p.track,playlist:p.playlist})}
function advanceMusic(delta=1){const state={...DEFAULT_MUSIC_STATE,...readJson(DB.musicState,DEFAULT_MUSIC_STATE)},pl=list(DB.playlists).find(x=>x.id===state.playlistId);if(!pl)return setMusicState({playing:false});const next=advanceState(state,pl,delta);setMusicState(next);return next}
function startMusicPlaylist(playlistId){const pl=list(DB.playlists).find(x=>x.id===playlistId);if(!pl)throw new Error('Playlist not found');const next=startPlaylist(readJson(DB.musicState,DEFAULT_MUSIC_STATE),pl);setMusicState(next);return next}
async function applySceneMusic(sceneName){const pl=list(DB.playlists).find(x=>Array.isArray(x.scenes)&&x.scenes.includes(sceneName));if(!pl)return;const state=readJson(DB.musicState,DEFAULT_MUSIC_STATE);if(state.playlistId===pl.id){if(Number(state.volume)!==Number(pl.volume))setMusicState({volume:pl.volume});return}startMusicPlaylist(pl.id)}

async function snapshot(manager){const [scenes,inputs,stream,record,stats,transition]=await Promise.all([manager.call('GetSceneList'),manager.call('GetInputList'),manager.call('GetStreamStatus').catch(()=>({outputActive:false,outputBytes:0,outputSkippedFrames:0,outputTotalFrames:0})),manager.call('GetRecordStatus').catch(()=>({outputActive:false})),manager.call('GetStats').catch(()=>({})),manager.call('GetCurrentSceneTransition').catch(()=>({transitionName:''}))]);const audio=[];for(const input of inputs.inputs||[]){try{const[m,v]=await Promise.all([manager.call('GetInputMute',{inputName:input.inputName}),manager.call('GetInputVolume',{inputName:input.inputName})]);audio.push({inputName:input.inputName,inputKind:input.inputKind,muted:Boolean(m.inputMuted),volume:Math.round((Number(v.inputVolumeMul)||0)*100)})}catch{}}const currentScene=scenes.currentProgramSceneName||'';let sceneItems=[];if(currentScene)try{sceneItems=((await manager.call('GetSceneItemList',{sceneName:currentScene})).sceneItems||[]).map(x=>({sceneItemId:x.sceneItemId,sourceName:x.sourceName,sourceType:x.sourceType,enabled:Boolean(x.sceneItemEnabled)}))}catch{}return{scenes:(scenes.scenes||[]).map(x=>x.sceneName),currentScene,sceneItems,audioInputs:audio,streaming:Boolean(stream.outputActive),recording:Boolean(record.outputActive),transitionName:transition.transitionName||'',health:{fps:Number(stats.activeFps||0),cpu:Number(stats.cpuUsage||0),memoryMb:Number(stats.memoryUsage||0),renderMissed:Number(stats.renderSkippedFrames||0),renderTotal:Number(stats.renderTotalFrames||0),outputSkipped:Number(stream.outputSkippedFrames||0),outputTotal:Number(stream.outputTotalFrames||0),bytes:Number(stream.outputBytes||0)}}}
async function sceneItems(manager,sceneName){if(!sceneName)return[];try{return((await manager.call('GetSceneItemList',{sceneName})).sceneItems||[]).map(x=>({sceneItemId:x.sceneItemId,sourceName:x.sourceName,sourceType:x.sourceType,enabled:Boolean(x.sceneItemEnabled)}))}catch{return[]}}

pool.on('status',status=>broadcastClients({type:'obs-status',connected:status.connected,targetId:status.id,targetName:status.name,state:status.state,error:status.lastError},status.id));
pool.on('obs-event',async({targetId,name,payload})=>{if(name==='CurrentProgramSceneChanged'){broadcastClients({type:'event',event:'scene',sceneName:payload.sceneName},targetId);applySceneMusic(payload.sceneName).catch(()=>{});const manager=pool.get(targetId);broadcastClients({type:'scene-items',data:await sceneItems(manager,payload.sceneName)},targetId)}else if(name==='InputMuteStateChanged')broadcastClients({type:'event',event:'mute',inputName:payload.inputName,muted:payload.inputMuted},targetId);else if(name==='InputVolumeChanged')broadcastClients({type:'event',event:'volume',inputName:payload.inputName,volume:Math.round((Number(payload.inputVolumeMul)||0)*100)},targetId);else if(name==='SceneItemEnableStateChanged')broadcastClients({type:'event',event:'source',sceneName:payload.sceneName,sceneItemId:payload.sceneItemId,enabled:payload.sceneItemEnabled},targetId);else if(name==='StreamStateChanged')broadcastClients({type:'event',event:'stream',active:payload.outputActive},targetId);else if(name==='RecordStateChanged')broadcastClients({type:'event',event:'record',active:payload.outputActive},targetId);else if(['SceneListChanged','InputCreated','InputRemoved','InputNameChanged'].includes(name)){const manager=pool.get(targetId);snapshot(manager).then(data=>broadcastClients({type:'snapshot',data},targetId)).catch(()=>{})}});

async function ensureBrowser(manager,sceneName,inputName,url,{width=64,height=64,audio=true}={}){const inputs=(await manager.call('GetInputList')).inputs||[];let items=await sceneItems(manager,sceneName);if(!items.some(x=>x.sourceName===inputName)){if(inputs.some(x=>x.inputName===inputName))await manager.call('CreateSceneItem',{sceneName,sourceName:inputName,sceneItemEnabled:true});else await manager.call('CreateInput',{sceneName,inputName,inputKind:'browser_source',inputSettings:{url,width,height,fps:30,reroute_audio:audio,shutdown:false},sceneItemEnabled:true})}try{await manager.call('SetInputSettings',{inputName,inputSettings:{url,width,height,fps:30,reroute_audio:audio,shutdown:false},overlay:true})}catch{}}
async function ensureSoundSource(manager,sceneName){await ensureBrowser(manager,sceneName,'OBSRemote • Custom Soundboard',`http://127.0.0.1:${PORT}/soundboard-player.html?token=${encodeURIComponent(PLAYER_SECRET)}`)}
async function ensureMusicSource(manager,allScenes=true){const scenes=(await manager.call('GetSceneList')).scenes||[],current=(await manager.call('GetSceneList')).currentProgramSceneName;const names=allScenes?scenes.map(x=>x.sceneName):[current].filter(Boolean);for(const sceneName of names)await ensureBrowser(manager,sceneName,'OBSRemote • Music',`http://127.0.0.1:${PORT}/music-player.html?token=${encodeURIComponent(PLAYER_SECRET)}`);return names}
async function playSound(manager,id){const sound=list(DB.sounds).find(x=>x.id===id);if(!sound)throw new Error('Sound not found');const scene=(await manager.call('GetSceneList')).currentProgramSceneName;if(!scene)throw new Error('No active scene');await ensureSoundSource(manager,scene);broadcast(soundPlayers,{type:'play',sound:{id:sound.id,name:sound.name,url:`/internal/media/sounds/${encodeURIComponent(sound.filename)}?token=${encodeURIComponent(PLAYER_SECRET)}`}});return sound}
async function getPreview(manager){const scenes=await manager.call('GetSceneList'),sceneName=scenes.currentProgramSceneName;if(!sceneName)throw new Error('No active scene');const shot=await manager.call('GetSourceScreenshot',{sourceName:sceneName,imageFormat:'jpg',imageWidth:960,imageCompressionQuality:68});return{sceneName,imageData:shot.imageData}}

function chooseInput(inputs,patterns){const normalized=(inputs||[]).map(i=>({...i,n:String(i.inputName).toLowerCase()}));for(const pattern of patterns){const hit=normalized.find(i=>pattern.test(i.n));if(hit)return hit.inputName}return''}
async function ensureScene(manager,name){const list=await manager.call('GetSceneList');if(!(list.scenes||[]).some(s=>s.sceneName===name))await manager.call('CreateScene',{sceneName:name})}
async function addExistingSource(manager,sceneName,sourceName){if(!sourceName)return false;const items=await sceneItems(manager,sceneName);if(items.some(x=>x.sourceName===sourceName))return true;try{await manager.call('CreateSceneItem',{sceneName,sourceName,sceneItemEnabled:true});return true}catch{return false}}
async function fitSource(manager,sceneName,sourceName,{x=0,y=0,width=1920,height=1080}={}){const item=(await sceneItems(manager,sceneName)).find(i=>i.sourceName===sourceName);if(!item)return;try{await manager.call('SetSceneItemTransform',{sceneName,sceneItemId:item.sceneItemId,sceneItemTransform:{positionX:x,positionY:y,boundsType:'OBS_BOUNDS_SCALE_INNER',boundsWidth:width,boundsHeight:height,alignment:5,boundsAlignment:5}})}catch{}}
async function ensureBackground(manager,sceneName,inputName,page){await ensureBrowser(manager,sceneName,inputName,`http://127.0.0.1:${PORT}/backgrounds/${page}`,{width:1920,height:1080,audio:false});await fitSource(manager,sceneName,inputName)}
async function buildSmartScenes(manager){const names=['Starting Soon','Game + Facecam','Xbox Fullscreen','Full Camera','Just Chatting','BRB','Ending'];for(const n of names)await ensureScene(manager,n);await ensureBackground(manager,'Starting Soon','OBSRemote • Starting Soon','starting.html');await ensureBackground(manager,'BRB','OBSRemote • BRB','brb.html');await ensureBackground(manager,'Ending','OBSRemote • Ending','ending.html');await ensureBackground(manager,'Full Camera','OBSRemote • Studio','studio.html');await ensureBackground(manager,'Just Chatting','OBSRemote • Studio Chat','studio.html');const inputs=(await manager.call('GetInputList')).inputs||[],camera=chooseInput(inputs,[/logitech/,/webcam/,/camera/,/cam\b/,/video capture/]),game=chooseInput(inputs,[/xbox/,/capture card/,/game capture/,/hdmi/,/elgato/,/capture/]),mic=chooseInput(inputs,[/mini mic/,/microphone/,/mic\b/,/audio input/]);if(game){await addExistingSource(manager,'Game + Facecam',game);await fitSource(manager,'Game + Facecam',game);await addExistingSource(manager,'Xbox Fullscreen',game);await fitSource(manager,'Xbox Fullscreen',game)}if(camera){await addExistingSource(manager,'Game + Facecam',camera);await fitSource(manager,'Game + Facecam',camera,{x:1420,y:780,width:470,height:264});await addExistingSource(manager,'Full Camera',camera);await fitSource(manager,'Full Camera',camera,{x:260,y:60,width:1400,height:960});await addExistingSource(manager,'Just Chatting',camera);await fitSource(manager,'Just Chatting',camera,{x:1040,y:360,width:760,height:680})}await ensureMusicSource(manager,true);for(const n of names)await ensureSoundSource(manager,n);return{scenes:names,camera,game,mic}}
async function findMic(manager){return chooseInput((await manager.call('GetInputList')).inputs||[],[/mini mic/,/microphone/,/mic\b/,/audio input/])}
async function smartAction(manager,preset){const map={starting:{scene:'Starting Soon',mute:true},game:{scene:'Game + Facecam',mute:false},xbox:{scene:'Xbox Fullscreen',mute:false},camera:{scene:'Full Camera',mute:false},chat:{scene:'Just Chatting',mute:false},brb:{scene:'BRB',mute:true},ending:{scene:'Ending',mute:true}},item=map[preset];if(!item)throw new Error('Unknown smart action');const scenes=await manager.call('GetSceneList');if(!(scenes.scenes||[]).some(s=>s.sceneName===item.scene))throw new Error('Build Smart Scenes first');await manager.call('SetCurrentProgramScene',{sceneName:item.scene});const mic=await findMic(manager);if(mic)await manager.call('SetInputMute',{inputName:mic,inputMuted:item.mute});return{...item,mic}}

function mediaPath(kind,filename){const base=kind==='music'?MUSIC_DIR:SOUND_DIR;const safeName=path.basename(filename);return path.join(base,safeName)}
app.get('/internal/media/:kind/:filename',(req,res)=>{if(!timingSafeEqualText(String(req.query.token||''),PLAYER_SECRET))return res.status(401).end();if(!['music','sounds'].includes(req.params.kind))return res.status(404).end();const file=mediaPath(req.params.kind,req.params.filename);if(!fs.existsSync(file))return res.status(404).end();res.setHeader('Cache-Control','private, max-age=3600');res.sendFile(file)});
app.get('/api/sounds/:id/file',requirePin,(req,res)=>{const x=list(DB.sounds).find(s=>s.id===req.params.id);if(!x)return res.status(404).end();const file=mediaPath('sounds',x.filename);if(!fs.existsSync(file))return res.status(404).end();res.sendFile(file)});
app.get('/api/music/:id/file',requirePin,(req,res)=>{const x=list(DB.music).find(s=>s.id===req.params.id);if(!x)return res.status(404).end();const file=mediaPath('music',x.filename);if(!fs.existsSync(file))return res.status(404).end();res.sendFile(file)});

app.get('/api/config',(_q,res)=>res.json({pinRequired:Boolean(REMOTE_PIN),aiEnabled:Boolean(OPENAI_API_KEY),aiModel:OPENAI_API_KEY?AI_MODEL:'',targets:TARGETS.map(({id,name})=>({id,name})),version:VERSION,features:{music:true,destinations:true,preflight:true,sharedObsConnection:true}}));
app.get('/api/health',(_q,res)=>res.json({ok:true,version:VERSION,uptime:Math.round(process.uptime()),targets:pool.statuses()}));
app.get('/api/preflight',requirePin,async(req,res)=>{const manager=pool.get(req.query.target||TARGETS[0].id),checks=[];try{await manager.ensureConnected();checks.push({id:'obs',ok:true,label:'OBS connected'});const snap=await snapshot(manager),inputs=snap.audioInputs.map(x=>x.inputName);checks.push({id:'scene',ok:Boolean(snap.currentScene),label:snap.currentScene?`Program scene: ${snap.currentScene}`:'No program scene'});checks.push({id:'mic',ok:Boolean(chooseInput(inputs.map(inputName=>({inputName})),[/mini mic/,/microphone/,/mic\b/])),label:'Main microphone detected'});checks.push({id:'camera',ok:Boolean(chooseInput((await manager.call('GetInputList')).inputs||[],[/logitech/,/webcam/,/camera/,/video capture/])),label:'Camera source detected'});try{const stat=fs.statfsSync(ROOT),free=stat.bavail*stat.bsize;checks.push({id:'disk',ok:free>5*1024**3,label:`Disk free: ${(free/1024**3).toFixed(1)} GB`})}catch{}checks.push({id:'music-source',ok:(await manager.call('GetInputList')).inputs?.some(x=>x.inputName==='OBSRemote • Music'),label:'Music bus installed'});res.json({ok:checks.every(x=>x.ok),checks,snapshot:snap})}catch(error){checks.push({id:'obs',ok:false,label:`OBS unavailable: ${error.message}`});res.status(503).json({ok:false,checks})}});

function uploadAudio(req,res,db,dir,kind){const{name,mime,data,filename,artist}=req.body||{},ext=audioExtension(mime,filename);if(!ext)return res.status(400).json({error:'Unsupported audio type'});if(typeof data!=='string'||!data)return res.status(400).json({error:'Missing audio data'});let buffer;try{buffer=Buffer.from(data,'base64')}catch{return res.status(400).json({error:'Invalid audio data'})}const max=kind==='track'?45*1024*1024:20*1024*1024;if(!buffer.length||buffer.length>max)return res.status(400).json({error:`Audio must be under ${Math.round(max/1024/1024)} MB`});if(!looksLikeAudio(buffer,ext))return res.status(400).json({error:'File signature does not match a supported audio format'});const id=crypto.randomUUID(),stored=`${id}${ext}`,item={id,name:safeText(name)||safeText(path.basename(filename||kind,path.extname(filename||'')))||kind,artist:safeText(artist),filename:stored,mime:String(mime||''),bytes:buffer.length,createdAt:new Date().toISOString()};fs.writeFileSync(path.join(dir,stored),buffer,{mode:0o600});const rows=list(db);rows.push(item);save(db,rows);res.status(201).json({item,[kind]:item})}
function deleteAudio(req,res,db,dir,kind){const rows=list(db),i=rows.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Not found'});const[x]=rows.splice(i,1);try{fs.unlinkSync(path.join(dir,path.basename(x.filename)))}catch{}save(db,rows);if(kind==='track'){const playlists=list(DB.playlists).map(p=>({...p,trackIds:(p.trackIds||[]).filter(id=>id!==x.id)}));save(DB.playlists,playlists);const state=readJson(DB.musicState,DEFAULT_MUSIC_STATE);if(state.trackId===x.id)setMusicState({trackId:null,playing:false,position:0})}res.json({ok:true})}
app.get('/api/sounds',requirePin,(_q,res)=>res.json({sounds:list(DB.sounds)}));app.post('/api/sounds',requirePin,(req,res)=>uploadAudio(req,res,DB.sounds,SOUND_DIR,'sound'));app.delete('/api/sounds/:id',requirePin,(req,res)=>deleteAudio(req,res,DB.sounds,SOUND_DIR,'sound'));
app.get('/api/music',requirePin,(_q,res)=>res.json(musicPayload()));app.post('/api/music',requirePin,(req,res)=>uploadAudio(req,res,DB.music,MUSIC_DIR,'track'));app.delete('/api/music/:id',requirePin,(req,res)=>deleteAudio(req,res,DB.music,MUSIC_DIR,'track'));
app.post('/api/playlists',requirePin,(req,res)=>{const tracks=list(DB.music),rows=list(DB.playlists),incoming=req.body||{},normalized=normalizePlaylist({...incoming,id:safeText(incoming.id)||crypto.randomUUID()},tracks.map(x=>x.id));if(!normalized.trackIds.length)return res.status(400).json({error:'Choose at least one valid track'});const i=rows.findIndex(x=>x.id===normalized.id);if(i>=0)rows[i]=normalized;else rows.push(normalized);save(DB.playlists,rows);res.json({playlist:normalized})});
app.delete('/api/playlists/:id',requirePin,(req,res)=>{const rows=list(DB.playlists),exists=rows.some(x=>x.id===req.params.id);save(DB.playlists,rows.filter(x=>x.id!==req.params.id));const state=readJson(DB.musicState,DEFAULT_MUSIC_STATE);if(state.playlistId===req.params.id)setMusicState({playlistId:null,trackId:null,playing:false,position:0});res.status(exists?200:404).json(exists?{ok:true}:{error:'Playlist not found'})});
app.post('/api/music/control',requirePin,(req,res)=>{try{const action=req.body?.action,state=readJson(DB.musicState,DEFAULT_MUSIC_STATE),tracks=list(DB.music);if(action==='play'){if(req.body.playlistId)startMusicPlaylist(req.body.playlistId);else if(req.body.trackId){if(!tracks.some(x=>x.id===req.body.trackId))throw new Error('Track not found');setMusicState({trackId:req.body.trackId,playlistId:null,playing:true,position:0})}else if(state.trackId)setMusicState({playing:true});else throw new Error('Choose a track or playlist first')}else if(action==='pause')setMusicState({playing:false});else if(action==='stop')setMusicState({playing:false,position:0});else if(action==='next')advanceMusic(1);else if(action==='prev')advanceMusic(-1);else if(action==='volume')setMusicState({volume:clamp(req.body.volume,0,100,25)});else throw new Error('Unknown music action');res.json(musicPayload())}catch(error){res.status(400).json({error:error.message})}});

function loadDestinationsRaw(){const rows=list(DB.destinations);let migrated=false;for(const row of rows){if(row.streamKey&&!row.streamKeyCipher){row.streamKeyCipher=sealText(row.streamKey,VAULT_KEY);delete row.streamKey;migrated=true}}if(migrated)save(DB.destinations,rows);return rows}
function publicDestination(row){return{id:row.id,name:row.name,type:row.type,serverUrl:row.serverUrl,hasStreamKey:Boolean(row.streamKeyCipher),enabled:row.enabled!==false,orientation:row.orientation,profile:row.profile,createdAt:row.createdAt}}
app.get('/api/destinations',requirePin,(_q,res)=>res.json({destinations:loadDestinationsRaw().map(publicDestination)}));
app.post('/api/destinations',requirePin,(req,res)=>{const rows=loadDestinationsRaw(),p=req.body||{},name=safeText(p.name),serverUrl=safeText(p.serverUrl,500);if(!name||!isRtmpUrl(serverUrl))return res.status(400).json({error:'A name and valid rtmp:// or rtmps:// server URL are required'});const old=rows.find(x=>x.id===p.id),plainKey=safeText(p.streamKey,1000),item={id:safeText(p.id)||crypto.randomUUID(),name,type:safeText(p.type)||'custom_rtmp',serverUrl,streamKeyCipher:plainKey?sealText(plainKey,VAULT_KEY):(old?.streamKeyCipher||''),enabled:p.enabled!==false,orientation:p.orientation==='vertical'?'vertical':'horizontal',profile:safeText(p.profile)||'1080p60',createdAt:old?.createdAt||new Date().toISOString()};const i=rows.findIndex(x=>x.id===item.id);if(i>=0)rows[i]=item;else rows.push(item);save(DB.destinations,rows);res.json({destination:publicDestination(item)})});
app.delete('/api/destinations/:id',requirePin,(req,res)=>{const rows=loadDestinationsRaw(),exists=rows.some(x=>x.id===req.params.id);save(DB.destinations,rows.filter(x=>x.id!==req.params.id));res.status(exists?200:404).json(exists?{ok:true}:{error:'Destination not found'})});
app.post('/api/destinations/:id/activate',requirePin,async(req,res)=>{try{const row=loadDestinationsRaw().find(x=>x.id===req.params.id);if(!row)throw new Error('Destination not found');const key=openText(row.streamKeyCipher,VAULT_KEY);if(!key)throw new Error('Stream key is missing');const manager=pool.get(req.body?.targetId||TARGETS[0].id),status=await manager.call('GetStreamStatus').catch(()=>({outputActive:false}));if(status.outputActive)throw new Error('Stop the active stream before changing destinations');await manager.call('SetStreamServiceSettings',{streamServiceType:'rtmp_custom',streamServiceSettings:{server:row.serverUrl,key,use_auth:false}});res.json({ok:true,message:`OBS output set to ${row.name}`})}catch(error){res.status(400).json({error:error.message})}});

function explicit(message,...terms){const m=String(message).toLowerCase();return terms.some(t=>m.includes(t))}
async function executeAiAction(manager,action,userMessage){switch(action.type){case'set_scene':await manager.call('SetCurrentProgramScene',{sceneName:String(action.scene)});return`Switched to ${action.scene}`;case'smart_mode':{const r=await smartAction(manager,String(action.mode));return`Smart mode: ${r.scene}`}case'mute':await manager.call('SetInputMute',{inputName:String(action.input),inputMuted:Boolean(action.muted)});return`${action.input} ${action.muted?'muted':'unmuted'}`;case'volume':await manager.call('SetInputVolume',{inputName:String(action.input),inputVolumeMul:clamp(action.volume,0,200,100)/100});return`${action.input} volume set`;case'play_sound':{const s=await playSound(manager,String(action.soundId));return`Played ${s.name}`}case'music':{const a=String(action.action);if(a==='play_playlist')startMusicPlaylist(String(action.playlistId));else if(a==='pause')setMusicState({playing:false});else if(a==='resume')setMusicState({playing:true});else if(a==='next')advanceMusic(1);else if(a==='volume')setMusicState({volume:clamp(action.volume,0,100,25)});else throw new Error('Unsupported music action');return'Music updated'}case'build_scenes':await buildSmartScenes(manager);return'Smart scenes built/repaired';case'stream':{const start=action.state==='start';if(!explicit(userMessage,start?'start stream':'stop stream',start?'go live':'end stream'))throw new Error('Streaming requires an explicit user request');const status=await manager.call('GetStreamStatus');if(start&&!status.outputActive)await manager.call('StartStream');if(!start&&status.outputActive)await manager.call('StopStream');return start?'Stream started':'Stream stopped'}case'record':{const start=action.state==='start';if(!explicit(userMessage,start?'start record':'stop record',start?'start recording':'stop recording'))throw new Error('Recording requires an explicit user request');const status=await manager.call('GetRecordStatus');if(start&&!status.outputActive)await manager.call('StartRecord');if(!start&&status.outputActive)await manager.call('StopRecord');return start?'Recording started':'Recording stopped'}default:throw new Error(`Unsupported AI action: ${action.type}`)}}
app.post('/api/ai',requirePin,async(req,res)=>{if(!OPENAI_API_KEY)return res.status(503).json({error:'AI assistant is not configured'});try{const message=String(req.body?.message||'').trim().slice(0,5000);if(!message)return res.status(400).json({error:'Message required'});const manager=pool.get(req.body?.targetId||TARGETS[0].id);const ctx={obs:await snapshot(manager),sounds:list(DB.sounds).map(({id,name})=>({id,name})),music:{state:musicPayload().state,playlists:list(DB.playlists).map(({id,name,trackIds,scenes})=>({id,name,tracks:trackIds.length,scenes}))},destinations:loadDestinationsRaw().map(({id,name,type,enabled,orientation,profile})=>({id,name,type,enabled,orientation,profile}))};const instructions='You are Studio AI, a streaming operations copilot. Return ONLY JSON with {"reply":"...","actions":[]}. Help with show planning, troubleshooting and live operations. Never invent OBS names. Allowed actions: set_scene, smart_mode(starting|game|xbox|camera|chat|brb|ending), mute, volume, play_sound, music(action play_playlist|pause|resume|next|volume), build_scenes, stream(start|stop), record(start|stop). Do not claim music is copyright-safe. Only use stream/record when explicitly requested.';const apiResponse=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:AI_MODEL,instructions,input:`Live context: ${JSON.stringify(ctx)}\nUser: ${message}`,text:{format:{type:'json_object'}},max_output_tokens:1000})});const result=await apiResponse.json();if(!apiResponse.ok)throw new Error(result?.error?.message||'AI request failed');let plan;try{plan=JSON.parse(result.output_text||'{}')}catch{throw new Error('AI returned invalid JSON')}const actionResults=[];for(const action of(Array.isArray(plan.actions)?plan.actions.slice(0,8):[])){try{actionResults.push({ok:true,action,result:await executeAiAction(manager,action,message)})}catch(error){actionResults.push({ok:false,action,error:error.message})}}res.json({reply:String(plan.reply||'Done.'),actionResults,snapshot:await snapshot(manager)})}catch(error){res.status(500).json({error:error.message||'AI assistant failed'})}});

async function handleCommand(ws,message){const manager=pool.get(ws.targetId);switch(message.action){case'set-scene':await manager.call('SetCurrentProgramScene',{sceneName:String(message.sceneName)});break;case'toggle-mute':{const s=await manager.call('GetInputMute',{inputName:String(message.inputName)});await manager.call('SetInputMute',{inputName:String(message.inputName),inputMuted:!s.inputMuted});break}case'set-mute':await manager.call('SetInputMute',{inputName:String(message.inputName),inputMuted:Boolean(message.muted)});break;case'set-volume':await manager.call('SetInputVolume',{inputName:String(message.inputName),inputVolumeMul:clamp(message.volume,0,200,100)/100});break;case'toggle-source':{const sceneName=String(message.sceneName||''),items=await sceneItems(manager,sceneName),item=items.find(i=>i.sceneItemId===Number(message.sceneItemId));if(!item)throw new Error('Source not found');await manager.call('SetSceneItemEnabled',{sceneName,sceneItemId:item.sceneItemId,sceneItemEnabled:!item.enabled});break}case'toggle-stream':{const s=await manager.call('GetStreamStatus');if(s.outputActive)await manager.call('StopStream');else await manager.call('StartStream');break}case'toggle-record':{const s=await manager.call('GetRecordStatus');if(s.outputActive)await manager.call('StopRecord');else await manager.call('StartRecord');break}case'panic-mute':{const s=await snapshot(manager);for(const input of s.audioInputs)try{await manager.call('SetInputMute',{inputName:input.inputName,inputMuted:true})}catch{}break}case'build-smart-scenes':{const result=await buildSmartScenes(manager);send(ws,{type:'smart-scenes-built',message:'Smart scenes repaired and music bus installed',result});break}case'smart-action':{const r=await smartAction(manager,String(message.preset));send(ws,{type:'toast',message:`${r.scene}${r.mic?` • ${r.mic} ${r.mute?'muted':'live'}`:''}`});break}case'play-custom-sound':{const s=await playSound(manager,String(message.soundId));send(ws,{type:'toast',message:`Played ${s.name}`});break}case'ensure-music-source':{const scenes=await ensureMusicSource(manager,true);send(ws,{type:'toast',message:`Music bus installed in ${scenes.length} scene${scenes.length===1?'':'s'}`});break}case'get-preview':send(ws,{type:'preview',...(await getPreview(manager)),at:Date.now()});break;case'refresh':send(ws,{type:'snapshot',data:await snapshot(manager)});break;default:throw new Error(`Unknown action: ${message.action}`)}}

wss.on('connection',async(ws,req)=>{let url;try{url=new URL(req.url,`http://${req.headers.host||'localhost'}`)}catch{ws.close(1008,'Bad request');return}const pin=url.searchParams.get('pin')||'',targetId=url.searchParams.get('target')||TARGETS[0].id;if(REMOTE_PIN&&!timingSafeEqualText(pin,REMOTE_PIN)){send(ws,{type:'error',message:'Incorrect remote PIN'});ws.close(1008,'Unauthorized');return}ws.targetId=String(pool.get(targetId).target.id);clients.add(ws);ws.on('message',async raw=>{try{const message=JSON.parse(raw.toString());if(message.action==='switch-target'){ws.targetId=String(pool.get(message.targetId).target.id);const manager=pool.get(ws.targetId);await manager.ensureConnected();send(ws,{type:'obs-status',connected:true,targetId:manager.target.id,targetName:manager.target.name,state:'connected'});send(ws,{type:'snapshot',data:await snapshot(manager)});return}await handleCommand(ws,message)}catch(error){send(ws,{type:'error',message:error.message||'Command failed'})}});ws.on('close',()=>clients.delete(ws));const manager=pool.get(ws.targetId);send(ws,{type:'obs-status',connected:manager.status().connected,targetId:manager.target.id,targetName:manager.target.name,state:manager.status().state,error:manager.status().lastError});try{await manager.ensureConnected();send(ws,{type:'obs-status',connected:true,targetId:manager.target.id,targetName:manager.target.name,state:'connected'});send(ws,{type:'snapshot',data:await snapshot(manager)});const p=musicPayload();send(ws,{type:'music-state',state:p.state,track:p.track,playlist:p.playlist})}catch(error){send(ws,{type:'obs-status',connected:false,targetId:manager.target.id,targetName:manager.target.name,state:'error',error:error.message});send(ws,{type:'error',message:`Could not connect to OBS: ${error.message}`})}});

function shutdown(signal){console.log(`\n${signal}: shutting down...`);server.close(()=>{});pool.close().finally(()=>process.exit(0));setTimeout(()=>process.exit(1),5000).unref()}process.on('SIGINT',()=>shutdown('SIGINT'));process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('unhandledRejection',error=>console.error('Unhandled rejection:',error));process.on('uncaughtException',error=>{console.error('Uncaught exception:',error);shutdown('uncaughtException')});
server.listen(PORT,'0.0.0.0',()=>{console.log(`\nOBS Remote ${VERSION} on port ${PORT}`);console.log(`Local: http://localhost:${PORT}`);for(const iface of Object.values(os.networkInterfaces()))for(const addr of iface||[])if(addr.family==='IPv4'&&!addr.internal)console.log(`LAN:   http://${addr.address}:${PORT}`);if(!REMOTE_PIN)console.warn('WARNING: REMOTE_PIN is not set. Do not expose this server publicly without authentication.');if(!OPENAI_API_KEY)console.warn('AI assistant disabled: OPENAI_API_KEY is not configured.');for(const manager of pool.managers.values())manager.ensureConnected().catch(()=>{})});
