import 'dotenv/config';
import express from 'express';
import http from 'node:http';
import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { WebSocketServer } from 'ws';
import OBSWebSocket, { EventSubscription } from 'obs-websocket-js';

const PORT=Number(process.env.PORT||3000),REMOTE_PIN=String(process.env.REMOTE_PIN||''),OPENAI_API_KEY=String(process.env.OPENAI_API_KEY||''),AI_MODEL=String(process.env.AI_MODEL||'gpt-5-mini');
const ROOT=process.cwd(),DATA=path.join(ROOT,'data'),SOUND_DIR=path.join(ROOT,'public','uploads','sounds'),MUSIC_DIR=path.join(ROOT,'public','uploads','music');
const DB={sounds:path.join(DATA,'sounds.json'),music:path.join(DATA,'music.json'),playlists:path.join(DATA,'playlists.json'),destinations:path.join(DATA,'destinations.json'),musicState:path.join(DATA,'music-state.json')};
for(const d of [DATA,SOUND_DIR,MUSIC_DIR])fs.mkdirSync(d,{recursive:true});
for(const [k,p] of Object.entries(DB))if(!fs.existsSync(p))fs.writeFileSync(p,k==='musicState'?JSON.stringify({playing:false,trackId:null,playlistId:null,index:0,volume:25,shuffle:false,loop:true,position:0},null,2):'[]');
const read=(p,f=[])=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return f}},write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const safe=(v,n=80)=>String(v||'').replace(/[<>]/g,'').trim().slice(0,n),extFor=(mime,name='')=>{const e=path.extname(name).toLowerCase();if(['.mp3','.wav','.m4a','.mp4','.ogg','.webm','.flac'].includes(e))return e;return {'audio/mpeg':'.mp3','audio/wav':'.wav','audio/x-wav':'.wav','audio/mp4':'.m4a','audio/ogg':'.ogg','audio/webm':'.webm','audio/flac':'.flac'}[mime]||'.mp3'};
function targets(){if(process.env.OBS_TARGETS_JSON){try{return JSON.parse(process.env.OBS_TARGETS_JSON)}catch{}}return[{id:'main',name:process.env.OBS_NAME||'Mac mini OBS',url:process.env.OBS_WS_URL||'ws://127.0.0.1:4455',password:process.env.OBS_WS_PASSWORD||''}]}
const TARGETS=targets();
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'55mb'}));app.use(express.static('public',{extensions:['html']}));
function requirePin(req,res,next){if(!REMOTE_PIN)return next();const pin=String(req.headers['x-remote-pin']||req.query.pin||'');if(pin!==REMOTE_PIN)return res.status(401).json({error:'Unauthorized'});next()}
const server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'}),soundWss=new WebSocketServer({server,path:'/sound-player'}),musicWss=new WebSocketServer({server,path:'/music-player'});const soundPlayers=new Set(),musicPlayers=new Set();
const send=(ws,p)=>{if(ws?.readyState===1)ws.send(JSON.stringify(p))},broadcast=(set,p)=>{for(const ws of set)send(ws,p)};
soundWss.on('connection',ws=>{soundPlayers.add(ws);ws.on('close',()=>soundPlayers.delete(ws))});
musicWss.on('connection',ws=>{musicPlayers.add(ws);send(ws,{type:'state',state:read(DB.musicState,{})});ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='progress'){const s=read(DB.musicState,{});Object.assign(s,{position:Number(m.position||0),duration:Number(m.duration||0),playing:!!m.playing});write(DB.musicState,s);broadcastClients({type:'music-state',state:s})}if(m.type==='ended')advanceMusic(1)}catch{}});ws.on('close',()=>musicPlayers.delete(ws))});

async function connectTarget(id){const t=TARGETS.find(x=>String(x.id)===String(id))||TARGETS[0],obs=new OBSWebSocket();await obs.connect(t.url,t.password||'',{eventSubscriptions:EventSubscription.All});return{obs,target:t}}
async function snapshot(obs){const [scenes,inputs,stream,record]=await Promise.all([obs.call('GetSceneList'),obs.call('GetInputList'),obs.call('GetStreamStatus').catch(()=>({outputActive:false})),obs.call('GetRecordStatus').catch(()=>({outputActive:false}))]);const audio=[];for(const i of inputs.inputs||[]){try{const [m,v]=await Promise.all([obs.call('GetInputMute',{inputName:i.inputName}),obs.call('GetInputVolume',{inputName:i.inputName})]);audio.push({inputName:i.inputName,muted:!!m.inputMuted,volume:Math.round((v.inputVolumeMul||0)*100)})}catch{}}const currentScene=scenes.currentProgramSceneName||'';let sceneItems=[];try{sceneItems=(await obs.call('GetSceneItemList',{sceneName:currentScene})).sceneItems.map(x=>({sceneItemId:x.sceneItemId,sourceName:x.sourceName,enabled:!!x.sceneItemEnabled}))}catch{}return{scenes:(scenes.scenes||[]).map(x=>x.sceneName),currentScene,sceneItems,audioInputs:audio,streaming:!!stream.outputActive,recording:!!record.outputActive}}
async function ensureBrowser(obs,sceneName,inputName,url,{w=64,h=64,audio=true}={}){let inputs=(await obs.call('GetInputList')).inputs||[];let items=[];try{items=(await obs.call('GetSceneItemList',{sceneName})).sceneItems||[]}catch{}if(!items.some(x=>x.sourceName===inputName)){if(inputs.some(x=>x.inputName===inputName))await obs.call('CreateSceneItem',{sceneName,sourceName:inputName,sceneItemEnabled:true});else await obs.call('CreateInput',{sceneName,inputName,inputKind:'browser_source',inputSettings:{url,width:w,height:h,fps:30,reroute_audio:audio,shutdown:false},sceneItemEnabled:true})}}
async function playSound(obs,id){const s=read(DB.sounds).find(x=>x.id===id);if(!s)throw new Error('Sound not found');const scene=(await obs.call('GetSceneList')).currentProgramSceneName;await ensureBrowser(obs,scene,'OBSRemote • Custom Soundboard',`http://127.0.0.1:${PORT}/soundboard-player.html`);broadcast(soundPlayers,{type:'play',sound:{...s,url:`/uploads/sounds/${s.filename}`}});return s}
async function ensureMusicSource(obs){const scene=(await obs.call('GetSceneList')).currentProgramSceneName;if(!scene)throw new Error('No active scene');await ensureBrowser(obs,scene,'OBSRemote • Music',`http://127.0.0.1:${PORT}/music-player.html`,{w:64,h:64,audio:true})}
function musicPayload(){const state=read(DB.musicState,{}),tracks=read(DB.music),playlists=read(DB.playlists),track=tracks.find(x=>x.id===state.trackId)||null,playlist=playlists.find(x=>x.id===state.playlistId)||null;return{state,track,playlist}}
function setMusicState(patch){const s={...read(DB.musicState,{}),...patch};write(DB.musicState,s);broadcast(musicPlayers,{type:'state',...musicPayload()});broadcastClients({type:'music-state',...musicPayload()});return s}
function choosePlaylistTrack(pl,state,delta=0){const ids=pl?.trackIds||[];if(!ids.length)return null;let idx=Number(state.index||0);if(state.shuffle&&ids.length>1){let n=idx;while(n===idx)n=Math.floor(Math.random()*ids.length);idx=n}else idx=(idx+delta+ids.length)%ids.length;return{trackId:ids[idx],index:idx}}
function advanceMusic(delta=1){const s=read(DB.musicState,{}),pl=read(DB.playlists).find(x=>x.id===s.playlistId);if(!pl)return s;const next=choosePlaylistTrack(pl,s,delta);if(!next)return s;return setMusicState({...next,playing:true,position:0})}
async function applySceneMusic(sceneName){const pls=read(DB.playlists),pl=pls.find(x=>Array.isArray(x.scenes)&&x.scenes.includes(sceneName));if(!pl)return;const s=read(DB.musicState,{});if(s.playlistId===pl.id)return;const first=choosePlaylistTrack(pl,{...s,index:-1,shuffle:!!pl.shuffle},1);if(first)setMusicState({playlistId:pl.id,...first,playing:true,volume:Number(pl.volume??25),shuffle:!!pl.shuffle,loop:pl.loop!==false,position:0})}

let clients=new Set();function broadcastClients(p){for(const ws of clients)send(ws,p)}
function attachEvents(client,obs){obs.on('CurrentProgramSceneChanged',async({sceneName})=>{send(client,{type:'event',event:'scene',sceneName});applySceneMusic(sceneName);try{send(client,{type:'snapshot',data:await snapshot(obs)})}catch{}});obs.on('InputMuteStateChanged',({inputName,inputMuted})=>send(client,{type:'event',event:'mute',inputName,muted:inputMuted}));obs.on('StreamStateChanged',({outputActive})=>send(client,{type:'event',event:'stream',active:outputActive}));obs.on('RecordStateChanged',({outputActive})=>send(client,{type:'event',event:'record',active:outputActive}))}
async function connectObs(client,id){if(client.obs)try{await client.obs.disconnect()}catch{}const {obs,target}=await connectTarget(id);client.obs=obs;client.targetId=target.id;attachEvents(client,obs);send(client,{type:'obs-status',connected:true,targetId:target.id,targetName:target.name});send(client,{type:'snapshot',data:await snapshot(obs)});send(client,{type:'music-state',...musicPayload()})}

app.get('/api/config',(_q,r)=>r.json({pinRequired:!!REMOTE_PIN,aiEnabled:!!OPENAI_API_KEY,aiModel:OPENAI_API_KEY?AI_MODEL:'',targets:TARGETS.map(({id,name})=>({id,name})),version:'4.0.0'}));app.get('/api/health',(_q,r)=>r.json({ok:true,version:'4.0.0'}));
app.get('/api/sounds',requirePin,(_q,r)=>r.json({sounds:read(DB.sounds)}));
app.post('/api/sounds',requirePin,(req,res)=>uploadAudio(req,res,DB.sounds,SOUND_DIR,'sound'));
app.delete('/api/sounds/:id',requirePin,(req,res)=>deleteAudio(req,res,DB.sounds,SOUND_DIR));
function uploadAudio(req,res,db,dir,kind){const{name,mime,data,filename,artist}=req.body||{};if(!String(mime||'').startsWith('audio/'))return res.status(400).json({error:'Audio files only'});let buf;try{buf=Buffer.from(data,'base64')}catch{return res.status(400).json({error:'Invalid audio'})}if(!buf.length||buf.length>45*1024*1024)return res.status(400).json({error:'Audio must be under 45 MB'});const id=crypto.randomUUID(),stored=id+extFor(mime,filename),item={id,name:safe(name)||safe(path.basename(filename||kind,path.extname(filename||''))),artist:safe(artist),filename:stored,mime,bytes:buf.length,createdAt:new Date().toISOString()};fs.writeFileSync(path.join(dir,stored),buf);const list=read(db);list.push(item);write(db,list);res.status(201).json({item,[kind]:item})}
function deleteAudio(req,res,db,dir){const list=read(db),i=list.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:'Not found'});const [x]=list.splice(i,1);try{fs.unlinkSync(path.join(dir,x.filename))}catch{}write(db,list);res.json({ok:true})}

app.get('/api/music',requirePin,(_q,r)=>r.json({tracks:read(DB.music),playlists:read(DB.playlists),...musicPayload()}));
app.post('/api/music',requirePin,(req,res)=>uploadAudio(req,res,DB.music,MUSIC_DIR,'track'));
app.delete('/api/music/:id',requirePin,(req,res)=>deleteAudio(req,res,DB.music,MUSIC_DIR));
app.post('/api/playlists',requirePin,(req,res)=>{const list=read(DB.playlists),p=req.body||{},item={id:p.id||crypto.randomUUID(),name:safe(p.name)||'Playlist',trackIds:Array.isArray(p.trackIds)?p.trackIds:[],shuffle:!!p.shuffle,loop:p.loop!==false,volume:Math.max(0,Math.min(100,Number(p.volume??25))),scenes:Array.isArray(p.scenes)?p.scenes.map(x=>safe(x)):[]};const i=list.findIndex(x=>x.id===item.id);if(i>=0)list[i]=item;else list.push(item);write(DB.playlists,list);res.json({playlist:item})});
app.delete('/api/playlists/:id',requirePin,(req,res)=>{write(DB.playlists,read(DB.playlists).filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.post('/api/music/control',requirePin,async(req,res)=>{const a=req.body?.action,s=read(DB.musicState,{});try{if(a==='play'){let patch={playing:true};if(req.body.playlistId){const pl=read(DB.playlists).find(x=>x.id===req.body.playlistId);if(!pl)throw new Error('Playlist not found');const first=choosePlaylistTrack(pl,{...s,index:-1,shuffle:!!pl.shuffle},1);patch={...patch,playlistId:pl.id,...first,shuffle:!!pl.shuffle,loop:pl.loop!==false,volume:Number(pl.volume??25),position:0}}if(req.body.trackId)patch={...patch,trackId:req.body.trackId,position:0};setMusicState(patch)}else if(a==='pause')setMusicState({playing:false});else if(a==='stop')setMusicState({playing:false,position:0});else if(a==='next')advanceMusic(1);else if(a==='prev')advanceMusic(-1);else if(a==='volume')setMusicState({volume:Math.max(0,Math.min(100,Number(req.body.volume))) });else throw new Error('Unknown music action');res.json(musicPayload())}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/destinations',requirePin,(_q,r)=>r.json({destinations:read(DB.destinations).map(x=>({...x,streamKey:x.streamKey?'••••••••':''}))}));
app.post('/api/destinations',requirePin,(req,res)=>{const list=read(DB.destinations),p=req.body||{};if(!safe(p.name)||!safe(p.serverUrl))return res.status(400).json({error:'Name and RTMP/RTMPS server URL are required'});if(!/^rtmps?:\/\//i.test(p.serverUrl))return res.status(400).json({error:'Server must start with rtmp:// or rtmps://'});const old=list.find(x=>x.id===p.id),item={id:p.id||crypto.randomUUID(),name:safe(p.name),type:safe(p.type)||'custom_rtmp',serverUrl:safe(p.serverUrl,500),streamKey:safe(p.streamKey,500)||old?.streamKey||'',enabled:p.enabled!==false,orientation:p.orientation==='vertical'?'vertical':'horizontal',profile:safe(p.profile)||'1080p60',createdAt:old?.createdAt||new Date().toISOString()};const i=list.findIndex(x=>x.id===item.id);if(i>=0)list[i]=item;else list.push(item);write(DB.destinations,list);res.json({destination:{...item,streamKey:item.streamKey?'••••••••':''}})});
app.delete('/api/destinations/:id',requirePin,(req,res)=>{write(DB.destinations,read(DB.destinations).filter(x=>x.id!==req.params.id));res.json({ok:true})});
app.post('/api/destinations/:id/activate',requirePin,async(req,res)=>{let obs;try{const d=read(DB.destinations).find(x=>x.id===req.params.id);if(!d)throw new Error('Destination not found');if(!d.streamKey)throw new Error('Stream key is missing');({obs}=await connectTarget(req.body?.targetId));await obs.call('SetStreamServiceSettings',{streamServiceType:'rtmp_custom',streamServiceSettings:{server:d.serverUrl,key:d.streamKey,use_auth:false}});res.json({ok:true,message:`OBS output set to ${d.name}`})}catch(e){res.status(400).json({error:e.message})}finally{if(obs)try{await obs.disconnect()}catch{}}});

app.post('/api/ai',requirePin,async(req,res)=>{if(!OPENAI_API_KEY)return res.status(503).json({error:'AI key not configured'});let obs;try{const message=String(req.body?.message||'').slice(0,4000),{obs:o}=await connectTarget(req.body?.targetId);obs=o;const ctx={obs:await snapshot(obs),sounds:read(DB.sounds).map(({id,name})=>({id,name})),music:musicPayload(),playlists:read(DB.playlists),destinations:read(DB.destinations).map(({id,name,type,enabled,orientation,profile})=>({id,name,type,enabled,orientation,profile}))};const instructions='You are Studio AI, a livestream producer copilot. Help plan shows, diagnose OBS, scenes, audio, music, destinations and cues. Return JSON with reply and actions. Allowed actions: set_scene, mute, volume, play_sound, music_play, music_pause, music_next, playlist_play. Never start/stop a stream unless the user explicitly asks; do not alter RTMP credentials. If planning, give a useful plan without actions.';const ar=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:AI_MODEL,instructions,input:`Context:${JSON.stringify(ctx)}\nUser:${message}`,text:{format:{type:'json_object'}},max_output_tokens:1200})});const out=await ar.json();if(!ar.ok)throw new Error(out?.error?.message||'AI failed');const plan=JSON.parse(out.output_text||'{}'),results=[];for(const a of Array.isArray(plan.actions)?plan.actions.slice(0,8):[]){try{if(a.type==='set_scene')await obs.call('SetCurrentProgramScene',{sceneName:a.scene});else if(a.type==='mute')await obs.call('SetInputMute',{inputName:a.input,inputMuted:!!a.muted});else if(a.type==='volume')await obs.call('SetInputVolume',{inputName:a.input,inputVolumeMul:Math.max(0,Math.min(2,Number(a.volume)/100))});else if(a.type==='play_sound')await playSound(obs,a.soundId);else if(a.type==='music_play')setMusicState({trackId:a.trackId,playing:true,position:0});else if(a.type==='music_pause')setMusicState({playing:false});else if(a.type==='music_next')advanceMusic(1);else if(a.type==='playlist_play'){const pl=read(DB.playlists).find(x=>x.id===a.playlistId);const first=choosePlaylistTrack(pl,{index:-1,shuffle:!!pl?.shuffle},1);if(pl&&first)setMusicState({playlistId:pl.id,...first,playing:true,volume:pl.volume,shuffle:pl.shuffle,loop:pl.loop,position:0})}else throw new Error('Unsupported action');results.push({ok:true,action:a})}catch(e){results.push({ok:false,action:a,error:e.message})}}res.json({reply:String(plan.reply||'Done.'),actionResults:results,snapshot:await snapshot(obs)})}catch(e){res.status(500).json({error:e.message})}finally{if(obs)try{await obs.disconnect()}catch{}}});

async function command(client,m){const obs=client.obs;if(!obs)throw new Error('OBS is not connected');if(m.action==='set-scene')await obs.call('SetCurrentProgramScene',{sceneName:m.sceneName});else if(m.action==='toggle-mute'){const x=await obs.call('GetInputMute',{inputName:m.inputName});await obs.call('SetInputMute',{inputName:m.inputName,inputMuted:!x.inputMuted})}else if(m.action==='set-volume')await obs.call('SetInputVolume',{inputName:m.inputName,inputVolumeMul:Math.max(0,Math.min(2,Number(m.volume)/100))});else if(m.action==='toggle-source'){const scene=m.sceneName||(await obs.call('GetSceneList')).currentProgramSceneName,items=(await obs.call('GetSceneItemList',{sceneName:scene})).sceneItems||[],x=items.find(i=>i.sceneItemId===Number(m.sceneItemId));if(x)await obs.call('SetSceneItemEnabled',{sceneName:scene,sceneItemId:x.sceneItemId,sceneItemEnabled:!x.sceneItemEnabled})}else if(m.action==='toggle-stream'){const x=await obs.call('GetStreamStatus');if(x.outputActive)await obs.call('StopStream');else await obs.call('StartStream')}else if(m.action==='toggle-record'){const x=await obs.call('GetRecordStatus');if(x.outputActive)await obs.call('StopRecord');else await obs.call('StartRecord')}else if(m.action==='play-custom-sound')await playSound(obs,m.soundId);else if(m.action==='get-preview'){const scene=(await obs.call('GetSceneList')).currentProgramSceneName,shot=await obs.call('GetSourceScreenshot',{sourceName:scene,imageFormat:'jpg',imageWidth:960,imageCompressionQuality:70});send(client,{type:'preview',sceneName:scene,imageData:shot.imageData,at:Date.now()})}else if(m.action==='ensure-music-source'){await ensureMusicSource(obs);send(client,{type:'toast',message:'Music source ready in current scene'})}else if(m.action==='refresh')send(client,{type:'snapshot',data:await snapshot(obs)});else throw new Error('Unknown action')}
wss.on('connection',async(ws,req)=>{const u=new URL(req.url,`http://${req.headers.host}`),pin=u.searchParams.get('pin')||'';if(REMOTE_PIN&&pin!==REMOTE_PIN){send(ws,{type:'error',message:'Incorrect remote PIN'});ws.close(1008);return}clients.add(ws);ws.on('message',async raw=>{try{const m=JSON.parse(raw);if(m.action==='switch-target')await connectObs(ws,m.targetId);else await command(ws,m)}catch(e){send(ws,{type:'error',message:e.message})}});ws.on('close',async()=>{clients.delete(ws);if(ws.obs)try{await ws.obs.disconnect()}catch{}});try{await connectObs(ws,u.searchParams.get('target')||TARGETS[0].id)}catch(e){send(ws,{type:'obs-status',connected:false});send(ws,{type:'error',message:`Could not connect to OBS: ${e.message}`})}});
server.listen(PORT,'0.0.0.0',()=>{console.log(`\nOBS Remote v4 running on ${PORT}`);console.log(`Local: http://localhost:${PORT}`);for(const list of Object.values(os.networkInterfaces()))for(const a of list||[])if(a.family==='IPv4'&&!a.internal)console.log(`LAN:   http://${a.address}:${PORT}`)});