import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

export function clamp(value,min,max,fallback=min){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
export function safeText(value,max=120){return String(value??'').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,max)}
export function isRtmpUrl(value){try{const u=new URL(String(value));return (u.protocol==='rtmp:'||u.protocol==='rtmps:')&&Boolean(u.hostname)}catch{return false}}
export function audioExtension(mime,filename=''){const ext=path.extname(String(filename)).toLowerCase();const allowed=new Set(['.mp3','.wav','.m4a','.mp4','.ogg','.webm','.flac']);if(allowed.has(ext))return ext;return {'audio/mpeg':'.mp3','audio/mp3':'.mp3','audio/wav':'.wav','audio/x-wav':'.wav','audio/mp4':'.m4a','audio/x-m4a':'.m4a','audio/ogg':'.ogg','audio/webm':'.webm','audio/flac':'.flac'}[String(mime).toLowerCase()]||''}
export function looksLikeAudio(buffer,ext=''){if(!Buffer.isBuffer(buffer)||buffer.length<4)return false;const h=buffer.subarray(0,16);const ascii=h.toString('ascii');if(ext==='.mp3')return ascii.startsWith('ID3')||(h[0]===0xff&&(h[1]&0xe0)===0xe0);if(ext==='.wav')return ascii.startsWith('RIFF')&&buffer.subarray(8,12).toString('ascii')==='WAVE';if(ext==='.ogg')return ascii.startsWith('OggS');if(ext==='.flac')return ascii.startsWith('fLaC');if(ext==='.m4a'||ext==='.mp4')return buffer.subarray(4,12).toString('ascii').includes('ftyp');if(ext==='.webm')return h[0]===0x1a&&h[1]===0x45&&h[2]===0xdf&&h[3]===0xa3;return false}
export function readJson(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return structuredClone(fallback)}}
export function atomicWriteJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;fs.writeFileSync(tmp,JSON.stringify(value,null,2)+'\n',{mode:0o600});fs.renameSync(tmp,file)}
export function ensureJson(file,fallback){if(!fs.existsSync(file))atomicWriteJson(file,fallback);return readJson(file,fallback)}
export function loadOrCreateSecret(file,bytes=32){fs.mkdirSync(path.dirname(file),{recursive:true});if(fs.existsSync(file)){const value=fs.readFileSync(file,'utf8').trim();if(value)return Buffer.from(value,'base64')}const secret=crypto.randomBytes(bytes);fs.writeFileSync(file,secret.toString('base64')+'\n',{mode:0o600});return secret}
export function sealText(plain,key){if(!plain)return'';const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const enc=Buffer.concat([cipher.update(String(plain),'utf8'),cipher.final()]);return ['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),enc.toString('base64url')].join('.')}
export function openText(value,key){if(!value)return'';if(!String(value).startsWith('v1.'))return String(value);const[,iv,tag,data]=String(value).split('.');const decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(data,'base64url')),decipher.final()]).toString('utf8')}
export function timingSafeEqualText(a,b){const aa=Buffer.from(String(a)),bb=Buffer.from(String(b));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)}
export function uniqueStrings(values,max=100){return [...new Set((Array.isArray(values)?values:[]).map(v=>safeText(v)).filter(Boolean))].slice(0,max)}
